Fix TypeError when there exists image with size None
When there exists image with size None(e.g.,images whose status is
queued), test_list_images_param_sort will raise TypeError:
TypeError: '<' not supported between instances of 'int' and 'NoneType',
So we should ignore images with size None.

Change-Id: Ie084c65303238eaeff0a753915356d72aa039434
Closes-Bug: #1905515