Add server tags schema in servers.py
Server tags testcases are introduced in microversion 2.26,
and if we run these testcases with min_microversion = 2.53, we
will get errors like
  "File "tempest/lib/services/compute/servers_client.py",
       line 836, in update_tag
    self.validate_response(schema.update_tag, resp, body)
   AttributeError: 'module' object has no attribute 'update_tag'"

So this is to add server tags schema in servers.py with
microversion higher than 2.26.

Implements blueprint: full-schema-for-all-microversions

Change-Id: Ifa246ca59f98f91334fe1a8ee16915558a98b76d