Fix a pointer to NotFound exception
Noticed an error in a run like this:

 Captured traceback-1:
 ~~~~~~~~~~~~~~~~~~~~~
     Traceback (most recent call last):
       File "tempest/api/compute/base.py", line 437, in _detach_volume
         except exceptions.NotFound:
     AttributeError: 'module' object has no attribute 'NotFound'

This exception was moved (I guess) but this spot was missed.

Closes-Bug: #1733674

Change-Id: Ia61eafe58ffc9658f70a8867c7729555a4e1d91c