Use assertLessEqual for downtime validation
The test was added as part of [1]. It should succeed
when downtime is within the limit but it fails as below even
if downtime is not higher than the allowed limit:-

AssertionError: 5.0 not less than 5 : Downtime \
of 5.0 seconds is higher than expected '5'

Fix it by using assertLessEqual so it fails only
if downtime is higher than the allowed limit.

[1] https://review.opendev.org/c/openstack/tempest/+/828686

Change-Id: I1bf87bd33aecf004d9cb650110f06454584f600c