Add missing volume snapshot skip
The following patch [1] that disables volume snapshots, fails with
the error: "'NfsDriver' object has no attribute 'create_snapshot'".
This patch adds the missing CONF.volume_feature_enabled.snapshot
skip to that test.

[1] https://review.openstack.org/#/c/395887

Change-Id: I5ad578a78d6cfd4186a8230ad472d4a7b92445c9
Closes-Bug: #1640646