Use keystoneclient 2.3.1
keystoneclient 3.0.0 was causing the below import error with glance commands
Use 2.3.1 instead
-------
+ ./contrail/contrail-tempest-init.sh
Traceback (most recent call last):
File "/root/tempest/.venv/bin/glance", line 7, in <module>
from glanceclient.shell import main
File "/root/tempest/.venv/local/lib/python2.7/site-packages/glanceclient/shell.py", line 44, in <module>
    from keystoneclient.openstack.common.apiclient import exceptions as ks_exc
    ImportError: No module named openstack.common.apiclient
-------