Get func.__class__.__name__ if no attribute __name__
In call_until_true, if func is wrapped with functools.partial,
getattr(func, '__name__') will get "AttributeError:
'functools.partial' object has no attribute '__name__'"

Now call_until_true supports args and kwargs that are passed
to func, so functools.partial is no longer needed, but it's
better for call_until_true to get func.__class__.__name__
if func has not attritube __name__.

Change-Id: Icc734e44af925655a31e7dcac04620352093cbeb
Closes-Bug: #1744210