Correct invalid client in ServersNegativeTestMultiTenantJSON
In ServersNegativeTestMultiTenantJSON's setUp, self.client
should be self.servers_client, otherwise we will get:
<AttributeError: "'ServersNegativeTestMultiTenantJSON' object
has no attribute 'client'">, and so we will encounter twice
unnecessary rebuild_server.

Change-Id: Ie5559bd4f1cbbb0b128946c21bd737585f79ffad