Update server details before getting fixed IP
If the validation.connect_method is set to "fixed" then
the ssh/ping validation fails in get_server_ip() on:
addresses = server['addresses'][CONF.validation.network_for_ssh]
    KeyError: 'addresses'

It seems that addresses information is not available in the initial
response upon server creation, from the compute API ref:
"Servers with status BUILD hide their addresses information."

The fix saves the returned full server response when waiting for
the server to become ACTIVE. Such response includes the Fixed IP
address (once the server is ACTIVE) and can be used for checking
the connection to the server later.

Change-Id: I1addbb52320deaa9e268eceb5dbd83f6da6c6f6a