Fix unbound local variable 'password error.
Fixes an issue causing the the following error when running tempest:

UnboundLocalError: local variable 'password' referenced before
assignment

Also, removes unused api_key param.

Change-Id: If9937a2ea51116f989316e32bb1209f9a8704a6e