Fixing tests when run_validation is set to true
Many tempest tests don't work if the run_validation option is
set to true. The validation resources provider tries to create
security groups and security group rules for these tests and it
fails with the following error:

AttributeError: 'SecurityGroupsClient' object has no attribute
'create_security_group_rule'

The reason of failures is that we have recently separated the security
groups client into two clients: security groups client and security group
rules client. This patch fixes the issue.

Change-Id: I548e1fecb6698ac2609fd1581633170ceb638506
Closes-Bug: #1482669