Add glare and taas to blacklist
This commit adds x/glare and x/tap-as-a-service to the BLACKLIST to
avoid sanity-job failures like following.

 Failed Plugins: x/glare, x/tap-as-a-service,
 + [[ -n x/glare, x/tap-as-a-service,  ]]
 + exit 1

It looks the root cause is related to pg_config installation but not
sure. So, this commit just blacklists them as a workaround.

 Error: pg_config executable not found.

Change-Id: I03c6f01593b8e414b5e111d0e0c971ae156da715